# Generated by Django 3.1 on 2020-09-17 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=7,
                                        primary_key=True, serialize=False)),
                ('usertype', models.CharField(choices=[('student', 'Student'), (
                    'admin', 'Admin'), ('security', 'Security')], default='student', max_length=8)),
                ('branch', models.CharField(choices=[('puc', 'PUC'), ('cse', 'CSE'), ('mech', 'MECH'), (
                    'chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL')], default='puc', max_length=5)),
                ('year', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('e1', 'E1'), (
                    'e2', 'E2'), ('e3', 'E3'), ('e4', 'E4')], default='p1', max_length=2)),
                ('in_campus', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('aadhar_no', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('Parent_name', models.CharField(max_length=50)),
                ('Parent_phn_no', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='personal_info', to='olms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=999)),
                ('proof', models.FileField(blank=True, default=None, null=True, upload_to='proofs/', validators=[
                 django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls'])])),
                ('out_date', models.DateTimeField(
                    blank=True, default=None, null=True)),
                ('in_date', models.DateTimeField(
                    blank=True, default=None, null=True)),
                ('actual_out_date', models.DateTimeField(
                    blank=True, default=None, null=True)),
                ('actual_in_date', models.DateTimeField(
                    blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('granted', 'granted'), ('rejected', 'rejected'), (
                    'on_leave', 'On Leave'), ('completed', 'Completed')], default='pending', max_length=9)),
                ('remark', models.CharField(default='No remark', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='leaveuser', to='olms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default=None, max_length=50)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('out_time', models.TimeField(blank=True, default=None, null=True)),
                ('in_time', models.TimeField(blank=True, default=None, null=True)),
                ('actual_in_time', models.TimeField(
                    blank=True, default=None, null=True)),
                ('actual_out_time', models.TimeField(
                    blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('granted', 'granted'), ('rejected', 'rejected'), (
                    'on_outing', 'On Outing'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='outinguser', to='olms.userprofile')),
            ],
        ),
    ]
