# Generated by Django 3.1.2 on 2020-11-06 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(choices=[('i1', 'I1'), ('i2', 'I2'), ('i3', 'I3'), ('k1', 'K1'), ('k2', 'K2'), ('k3', 'K3'), ('k4', 'K4')], default='i2', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='in_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='out_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls', 'jpeg', 'img'])]),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('granted', 'granted'), ('rejected', 'rejected'), ('on_leave', 'On Leave'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=9),
        ),
    ]
