# Generated by Django 3.1.2 on 2020-11-06 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0002_auto_20201106_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Parent_phn_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(
                message='Phone number should only contain numbers and should have exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='aadhar_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(
                message='Aadhar number should only contain numbers and should have exactly 12 digits', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(
                message='Phone number should only contain numbers and should have exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
